// packages/react-component-titles/src/useComponentTitle.ts
import {
  IDOMTitleComponentData,
  handleRegisterFactory,
  handleUnregisterFactory,
  onMount,
  onUnmount,
  registerFactory,
  revertTitleFactory,
} from "@jvllmr/component-titles-core";
import { MutableRefObject, useEffect, useMemo, useRef } from "react";
import { v4 as uuidv4 } from "uuid";

function refSetter<T>(ref: MutableRefObject<T>) {
  return (value: T) => (ref.current = value);
}

function refGetter<T>(ref: MutableRefObject<T>) {
  return () => ref.current;
}

export function useComponentTitle(title: string) {
  const uuid = useRef(uuidv4());
  const mountedTitle = useRef("");
  const titleBeforeMount = useRef("");
  const behindMe = useRef<IDOMTitleComponentData>();
  const beforeMe = useRef<IDOMTitleComponentData>();
  const iAmLast = useRef(true);

  const handleRegister = useMemo(
    () =>
      handleRegisterFactory({
        iAmLast: refGetter(iAmLast),
        mountedTitle: refGetter(mountedTitle),
        myId: refGetter(uuid),
        titleBeforeMount: refGetter(titleBeforeMount),
        setBehindMe: refSetter(behindMe),
        setIAmLast: refSetter(iAmLast),
      }),
    [],
  );
  const handleUnregister = useMemo(
    () =>
      handleUnregisterFactory({
        beforeMe: refGetter(beforeMe),
        behindMe: refGetter(behindMe),
        mountedTitle: refGetter(mountedTitle),
        myId: refGetter(uuid),
        titleBeforeMount: refGetter(titleBeforeMount),
        setBeforeMe: refSetter(beforeMe),
        setBehindMe: refSetter(behindMe),
        setIAmLast: refSetter(iAmLast),
        setTitleBeforeMount: refSetter(titleBeforeMount),
      }),
    [],
  );
  const revertTitle = useMemo(
    () =>
      revertTitleFactory({
        beforeMe: refGetter(beforeMe),
        behindMe: refGetter(behindMe),
        mountedTitle: refGetter(mountedTitle),
        titleBeforeMount: refGetter(titleBeforeMount),
      }),
    [],
  );
  const register = useMemo(
    () =>
      registerFactory({
        revertTitle,
        beforeMe: refGetter(beforeMe),
        behindMe: refGetter(behindMe),
        mountedTitle: refGetter(mountedTitle),
        myId: refGetter(uuid),
        titleBeforeMount: refGetter(titleBeforeMount),
        setBeforeMe: refSetter(beforeMe),
        setBehindMe: refSetter(behindMe),
        setIAmLast: refSetter(iAmLast),
        setMountedTitle: refSetter(mountedTitle),
        setTitleBeforeMount: refSetter(titleBeforeMount),
      }),
    [],
  );
  useEffect(() => {
    onMount({ handleRegister, handleUnregister });
    return () => {
      onUnmount({
        beforeMe: refGetter(beforeMe),
        behindMe: refGetter(behindMe),
        handleRegister,
        handleUnregister,
        mountedTitle: refGetter(mountedTitle),
        myId: refGetter(uuid),
        revertTitle,
        titleBeforeMount: refGetter(titleBeforeMount),
      });
    };
  }, []);

  useMemo(() => {
    register(title);
  }, []);

  useEffect(() => {
    register(title);
  }, [title]);
}

// packages/solid-component-titles/src/useComponentTitle.ts
import {
  IDOMTitleComponentData,
  handleRegisterFactory,
  handleUnregisterFactory,
  onMount as onTitleMount,
  onUnmount,
  registerFactory,
  revertTitleFactory,
} from "@jvllmr/component-titles-core";
import { createEffect, createMemo, onCleanup, onMount } from "solid-js";
import { v4 as uuidv4 } from "uuid";

function refSetter<TData>(data: TData, key: keyof TData) {
  return (value: TData[keyof TData]) => (data[key] = value);
}

function refGetter<TData, TDataKey extends keyof TData>(
  data: TData,
  key: TDataKey
): () => TData[TDataKey] {
  return () => data[key];
}

export function useComponentTitle(title: string) {
  const componentInfo: {
    iAmLast: boolean;
    mountedTitle: string;
    uuid: string;
    titleBeforeMount: string;
    behindMe: IDOMTitleComponentData | undefined;
    beforeMe: IDOMTitleComponentData | undefined;
  } = {
    iAmLast: true,
    mountedTitle: "",
    uuid: uuidv4(),
    titleBeforeMount: "",
    behindMe: undefined,
    beforeMe: undefined,
  };

  const handleRegister = createMemo(() =>
    handleRegisterFactory({
      iAmLast: refGetter(componentInfo, "iAmLast"),
      mountedTitle: refGetter(componentInfo, "mountedTitle"),
      myId: refGetter(componentInfo, "uuid"),
      titleBeforeMount: refGetter(componentInfo, "titleBeforeMount"),
      setBehindMe: refSetter(componentInfo, "behindMe"),
      setIAmLast: refSetter(componentInfo, "iAmLast"),
    })
  );
  const handleUnregister = createMemo(
    () =>
      handleUnregisterFactory({
        beforeMe: refGetter(componentInfo, "beforeMe"),
        behindMe: refGetter(componentInfo, "behindMe"),
        mountedTitle: refGetter(componentInfo, "mountedTitle"),
        myId: refGetter(componentInfo, "uuid"),
        titleBeforeMount: refGetter(componentInfo, "titleBeforeMount"),
        setBeforeMe: refSetter(componentInfo, "beforeMe"),
        setBehindMe: refSetter(componentInfo, "behindMe"),
        setIAmLast: refSetter(componentInfo, "iAmLast"),
        setTitleBeforeMount: refSetter(componentInfo, "titleBeforeMount"),
      }),
    []
  );
  const revertTitle = createMemo(
    () =>
      revertTitleFactory({
        beforeMe: refGetter(componentInfo, "beforeMe"),
        behindMe: refGetter(componentInfo, "behindMe"),
        mountedTitle: refGetter(componentInfo, "mountedTitle"),
        titleBeforeMount: refGetter(componentInfo, "titleBeforeMount"),
      }),
    []
  );
  const register = createMemo(() =>
    registerFactory({
      revertTitle,
      beforeMe: refGetter(componentInfo, "beforeMe"),
      behindMe: refGetter(componentInfo, "behindMe"),
      mountedTitle: refGetter(componentInfo, "mountedTitle"),
      myId: refGetter(componentInfo, "uuid"),
      titleBeforeMount: refGetter(componentInfo, "titleBeforeMount"),
      setBeforeMe: refSetter(componentInfo, "beforeMe"),
      setBehindMe: refSetter(componentInfo, "behindMe"),
      setIAmLast: refSetter(componentInfo, "iAmLast"),
      setMountedTitle: refSetter(componentInfo, "mountedTitle"),
      setTitleBeforeMount: refSetter(componentInfo, "titleBeforeMount"),
    })
  );

  onMount(() => {
    onTitleMount({
      handleRegister: handleRegister(),
      handleUnregister: handleUnregister(),
    });
  });

  onCleanup(() => {
    onUnmount({
      handleRegister: handleRegister(),
      handleUnregister: handleUnregister(),
      titleBeforeMount: refGetter(componentInfo, "titleBeforeMount"),
      beforeMe: refGetter(componentInfo, "beforeMe"),
      myId: refGetter(componentInfo, "uuid"),
      behindMe: refGetter(componentInfo, "behindMe"),
      mountedTitle: refGetter(componentInfo, "mountedTitle"),
      revertTitle: revertTitle(),
    });
  });

  createEffect(() => {
    register()(title);
  });
}
